### ISSUE TITLE
> > 课程似乎已经进不去了, 不过有群友提前下载了下来：https://pan.baidu.com/s/12IrKc-PaX1Z7SeGnsUkh2g 提取码：zy7m

### ISSUE THREAD

**Issue by Alafun** [nju-kaoyan/nju_ai_22#2]
> > 课程似乎已经进不去了, 不过有群友提前下载了下来：https://pan.baidu.com/s/12IrKc-PaX1Z7SeGnsUkh2g 提取码：zy7m

失效了

_Originally posted by @Alafun in https://github.com/nju-kaoyan/nju_ai_20/issues/1#issuecomment-1110628638_

**Comment by ThyrixYang** [comment]
应该找不到了, 你进群问吧...
